# 1 Customer Analysis

# 1. Find Total customer
select count(*) from  customers;

# 2.Count of Customer by Gender 
select gender,count(*) as total
from customers
group by gender;


# 3. Top 10 cities with most customer.
select city,count(*) as customer_count from customers
group by city
order by customer_count desc
limit 10 ;

# 4.Recently Join Customer(last 30 days).
select * from customers where created_at >= now()-interval 30 day;

# 5.Top 10 State wise most customers.
select state,count(*) as customer_count from customers
group by state
order by customer_count desc
limit 10 ;

# 6. Top 10 customer who  placed the most orders
select c.customer_id,c.first_name,c.last_name,count(o.order_id) as total_order
from customers c 
join orders o on
c.customer_id=o.customer_id
group by customer_id
order by total_order desc
limit 10;

# 2.Sales and order Analysis

# 1. monthly sale trend over time.
select date_format(order_date,'%y-%m') as month,
count(order_id) as Total_order from orders
group by month
order  by month;

# 2. Total revenue Generated(After Discount)
select sum((price-discount)*quantity)
from order_items;

# 3.Rating
select  oi.discount,r.rating from reviews r 
inner join
order_items oi on oi.product_id=r.product_id;


# 3.payment Mode Distrubution.
select payment_mode,count(order_id) as total_order 
from orders
group by payment_mode;


# 3. which state that bringing hightest amount of revenue ?
select o.state,sum((oi.price-discount)*quantity) as Total_revenue
from orders o join
order_items as oi
on o.order_id=oi.order_id 
group by state
order by Total_revenue desc;

# 3.Product and Catogory Analytics
 # 1 Top 10 best selling product (Quantity wise)
 
select p.product_id,p.name as product_name,
sum(oi.quantity) as total_quantity_sold
from products p
join order_items oi
on p.product_id=oi.product_id
group by product_id
order by total_quantity_sold desc
limit 10 ;


# 2. least selling product (dead)
select p.product_id,p.name as product_name,p.brand,
    coalesce(sum(oi.quantity)) as quantity_sold
from products as p 
left join order_items oi
on p.product_id=oi.product_id
group by product_id,p.brand,product_name
order by quantity_sold limit 5 ;



# 3. revenue Generated by catagory
select c.name as categary,
sum((oi.price-oi.discount)*oi.quantity) as total_revenue
from categories as c
join products p
on c.category_id=p.category_id
join order_items oi
on p.product_id=oi.product_id
group by c.category_id
order by total_revenue desc ;

# 4.Review and customer experience analysis

#  1.average rating for each product 
select p.product_id,p.name as product_name,
avg(r.rating) as avg_rating from products p
join reviews r
on p.product_id =r.product_id
group by product_id
order by avg_rating desc;

# 2 Top 10 highest reviews product.
select p.product_id,p.name as product_name,p.brand,
count(r.rating) as rating from products p
join reviews r
on p.product_id =r.product_id
group by product_id
order by rating desc
limit 10;

# 3 sentiment Distrubution.
select sentiment ,count(*) As count
from reviews 
group by sentiment;


# Advanced Analytics

# 1.identifying customer reapting  order
select customer_id,total_order
from(select customer_id, count(order_id) as total_order
from orders group by customer_id )as t
order by total_order desc;

# 2.Customer who never place any order.
select first_name ,last_name,customer_id
 from customers 
where customer_id  not in (select customer_id from orders);

# 3.Most return/Cancelled order
select count(*) as cancel_order from orders 
where status='cancelled';


# 4.which product are frequently bought together (market basket analysis)
select oi1.product_id as product_A,
oi2.product_id as product_B,
count(*) as Fequency
from order_items oi1
join order_items oi2
on oi1.order_id=oi2.order_id and oi1.product_id < oi2.product_id
group by product_A,product_B
order by Fequency desc
limit 20;


# views :A view is a saved sql query that behave like a virtual table it does not storage data physically it only store the query structure.
# uses :1 Reusability ,2.simplfies analytics ,3.secuirity 4.performance

# 1 .customer order summery -It show us each customer's  total orders ,total revenue and average order value.
 create view vw_customer_order_summery as 
       select 
           c.customer_id,
           concat(c.first_name," ",c.last_name) as Customer_name,
           count(o.order_id) as Total_orders,
           sum((oi.price-oi.discount)*oi.quantity)as Total_revenue,
           avg((oi.price-oi.discount)*oi.quantity)as Avg_order_value
	   from customers  c
       left join orders o on
       c.customer_id=o.customer_id
       left join order_items oi
       on o.order_id=oi.order_id
       group by c.customer_id,Customer_name;


# 2.Product perfomance view : product Selling the most 
create view vw_product_performance as
	select p.product_id,
         p.name as Product_name,
         c.name as Category,
         p.brand,
         sum(oi.quantity) as unit_sold,
		 sum((oi.price-oi.discount)*oi.quantity)as Total_revenue,
         p.stock
	from products as p 
    left join categories c on p.category_id=c.category_id
    left join order_items oi on p.product_id=oi.product_id
    group by p.product_id,Product_name;


# 3.daily Sales View : order date,total order,unit sold , total revenue .
create view vw_daily_sales as 
	select date(o.order_date) as Order_date,
		count(distinct o.order_id) as Total_order,
		sum(oi.quantity) as Unit_sold,
		sum((oi.price-oi.discount)*oi.quantity)as Total_revenue
    from orders o
    left join order_items oi
	on o.order_id=oi.order_id
	group by Order_date
    order by Order_date;


# 4 review sentiment : PRODUCT id ,total review,avg rating, positive review,negative review. 
create view vw_review_sentiment as 
      select p.product_id,
             p.name as product_name,
            count(review_id) as Total_review,
            avg(rating) as avg_rating,
            sum(case when sentiment = 'Positive' then 1 else 0 end) as Positive_Review,
			sum(case when sentiment = 'Negative' then 1 else 0 end) as Negative_Review,
			sum(case when sentiment = 'Neutral' then 1 else 0 end) as Neutral_Review
      from  reviews r
	  left join products p
      on p.product_id=r.product_id
	  group by product_id;


#---------------------------------------------------------------#
# Stored Procedure : A stored procedure is SQL block of code saved in the database that execute like a function
# uses : 1.Automate Task ,2.Reusable  3 Fast,4.Secuirity , 5.Standardization .

 # 1. Get Customers Order History
 delimiter $$ 
 create procedure sp_get_customer_order_history( in p_customer_id int)
 begin
    select  
        o.order_id,
        o.order_date,
        o.status,
        sum((oi.price-oi.discount)*oi.quantity) as order_amount
	from orders o
    join order_items oi on o.order_id=oi.order_id
    where o.customer_id=p_customer_id
    group by o.order_id,o.order_date,o.status
    order by o.order_date desc;
end $$
delimiter ;


      
call sp_get_customer_order_history(200)

# 2. Update stoke After Orders
delimiter $$
create procedure sp_update_stock(in p_product_id int ,p_quantity int)
begin
    update products
    set stock=stock-p_quantity
    where product_id=p_product_id;
    
end $$
delimiter ;


# 3. Top N revenue Product
delimiter $$
create procedure sp_top_products(in p_n int)
    begin
    select p.product_id,
    p.name,
	sum((oi.price-oi.discount)*oi.quantity) as Total_revenue
     from products p left join
     order_items oi on
     p.product_id=oi.product_id
     group by p.product_id,p.name
     order by Total_revenue desc
     limit 10;
end $$
delimiter ;

    

# 4.Monthly Revenue Sales Report
delimiter $$
create procedure sp_monthly_sales(in p_year int,p_month int)
begin 
  select
     date(o.order_date) as order_date,
     count(o.order_id) as Total_order,
	sum((oi.price-oi.discount)*oi.quantity) as Total_revenue
 from  orders o 
 join order_items oi 
 on o.order_id=oi.order_id
 where year(order_date)=p_year and month(order_date)=p_month
 group by order_date
 order by order_date;
 end  $$
 delimiter ;
     





